name: Web Client Pull Request
on:
  push:
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./web-client

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: npm install
        run: npm ci

      - name: npm build
        run: npm run build

      - name: npm lint
        run: npm run lint
